### ISSUE TITLE
HTTP Error 404: Not found (wasm-binaries-arm64.tbz2)

### ISSUE THREAD

**Issue by patham9** [emscripten-core/emsdk#1040]
Execution of
`./emsdk install latest`
leads to downloading of
`https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/edabe25af34554d19c046078f853999b074259ca/wasm-binaries-arm64.tbz2`
which does not exist on this server, so can also not be downloaded with other tools.
Is there any workaround for this?

`uname -a` result:
`Linux fedora 5.14.10-300.fc35.aarch64 #1 SMP Thu Oct 7 20:32:40 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by sbc100** [comment]
This is to be expected due to #1011 not being fully finished yet.   There are only binaries available for certain versions.     For now you will need to `./emsdk install 3.1.8`.   We should probably add

(a) a warning for anyone using arm64/linux so they know that its currently only best-effort supported.
(b) a way to pin a different `latest` for arm64.

**Comment by thadk** [comment]
#1011 appears to be merged but [the entry](https://github.com/emscripten-core/emsdk/blob/main/emsdk_manifest.json#L111) in that line still doesn't exist.
