### ISSUE TITLE
std::ifstream open file failed

### ISSUE THREAD

**Issue by luyahan** [emscripten-core/emsdk#1197]
```
#include <iostream>
#include <fstream>
 
int main(){
  std::ifstream f("/proc/cpuinfo");
  if (!f.is_open()) {
    std::cerr << "failed to open /proc/cpuinfo\n";
    return -1;
  }
  return 0;
}
```

build it by `emcc ./opencpu.cpp -sENVIRONMENT=shell -o opencpu.js`. run `d8 ./opencpu.js`

return 
```
failed to open /proc/cpuinfo
```

Does emcc support std::ifstream?

**Comment by sbc100** [comment]
This is expected behaviour.  Emscripten uses virtual filesystem and `/proc/cpuinfo` doesn't exist in it.

We do have a mode called `-sNODRAWSFS` that you can use such that when running under node, and real filesystem is used.  But it only works in node and of course `/proc/cpuinfo` would only work if you are running on linux.

If you are suggesting that we should add some kind of emulation of `/proc/cpuinfo` or the emscripten VFS than that would be different question.
