### ISSUE TITLE
Please bump Node version on emscripten/emsdk

### ISSUE THREAD

**Issue by skhaz** [emscripten-core/emsdk#1303]
Could it be possible to bump the Node version to the current LTS? The Docker image contains version 12, which is quite old.

**Comment by sbc100** [comment]
Which docker images contains node 12?   IIRC we updates for node 16 recently.  See #1232.

Regarding updated from 16 to 18 (which is currently LTS) that has beed discussed at length in other issues such as #1173 and #1284.   Since we landed #1189, the version of node used internally with emsdk should have less impact (since it not longer adds node to the path if there already exists one).

**Comment by skhaz** [comment]
I have found Node 16 (not 12) on `/emsdk/node/16.20.0_64bit/bin` in `emscripten/emsdk:3.1.49`

**Comment by skhaz** [comment]
Yes, that's more than enough, I was using Node to run WebAssembly, but I changed my mind and will execute the WebAssembly with wasmtime because I have more control (I was using emscripten as base, to run a simple script in JavaScript).

Thank you!
