### ISSUE TITLE
compile wams64 using bazel mode

### ISSUE THREAD

**Issue by phoenix20162016** [emscripten-core/emsdk#1362]
in default bazel config， the build env is under 32bit mode, how can i switch to 64bit mode

**Comment by sbc100** [comment]
To build for wasm64 you can add `-sMEMORY64` to you compile and link commands.

**Comment by phoenix20162016** [comment]
![image](https://github.com/emscripten-core/emsdk/assets/18574396/d83dfb70-8dc1-4dd2-aecc-5fe560a11d78)
follows your suggestion， another error occurs, the following is my bazel configuration
![image](https://github.com/emscripten-core/emsdk/assets/18574396/b463551f-0870-4a7b-b992-387eab79cf5c)

in the fold of the compile tools, the wasm64-emscripten dir is really  not exist

**Comment by sbc100** [comment]
I see, yes we don't currently wasm64 versions of any core libraries in the bazel toolchain.    I think this is the same as  https://github.com/emscripten-core/emsdk/issues/807.    Perhaps we can close this and continue the discussion there?

**Comment by wzheng21** [comment]
@phoenix20162016 I had the same problem as yours. For whoever having similar issues, I had to patch emsdk setting `FROZEN_CACHE = False` in config.py, then the issue becomes `read-only blabla` error, basically indicating emscripten tries to compile libraries and writes into a temporary cache folder but failed.

This of course would fail, due to bazel's idea of keeping builds hermitian. The following are the two different workarounds I tested with my work:

1. Disable bazel sandbox mode. Just specify `--spawn_strategy=local`. Be careful when using this, especially if this is not a toy project
2. Don't play with sandbox, but specify `--action_env=EM_CACHE=~/.cache/emscripten_cache`. When FROZEN_CACHE is False, emscripten will try to write to `~/.emscripten_cache`, which will definitely fail in bazel sandbox mode due to permissions. Writing to `~/.cache` folder, however, is allowed.

Hope this is helpful for anyone getting stuck with this issue.
