### ISSUE TITLE
[Question] Why use JAVA_HOME instead of EMSDK_JAVA_HOME?

### ISSUE THREAD

**Issue by D7x7z49** [emscripten-core/emsdk#1483]
When running `./emsdk activate latest`, I noticed the environment variables `EMSDK_NODE` and `EMSDK_PYTHON`. 
However, for Java, the variable used is `JAVA_HOME` instead of `EMSDK_JAVA_HOME`. Why is this the case?

**Comment by sbc100** [comment]
emsdk doesn't use java for anything anymore so these should not be needed.

**Comment by sbc100** [comment]
Sorry I take that back, it looks like we do still install java on with the windows version of the SDK.  I have PR up to remove it: https://github.com/emscripten-core/emsdk/pull/1324

I think the reason JAVA_HOME was used is because that is the standard environment variable used by java itself so this makes things just work.   It was probably not most hermetic way to embed java since it means the whole system would then use the emsdk version of java.
