### ISSUE TITLE
emsdk construct_env on Windows nukes local paths

### ISSUE THREAD

**Issue by iboB** [emscripten-core/emsdk#189]
Windows-only repro: 
* open a console
* add something to the path: `> set path=%path%;something`
* `> emsdk_env`
* Your something is gone.

(conversely remove something and see it reappear)

The problem is that emsdk gets the path to which it appends from the registry so any local changes are lost. I was tempted to make a pull request which fixes this, but since specific effort is made for it to work like this, I decided to ask first.

The relevant code is here: [emsdk#L1935](https://github.com/juj/emsdk/blob/7a0e27441eda6cb0e3f1210e6837cae4b080ab4c/emsdk#L1935)

Why get the system path in such convoluted way? Why query the registry instead of just use the path environment variable?

**Comment by juj** [comment]
The reason for getting the PATH from registry is that someone reported before that there's a bug that emsdk PATH setting nukes %VAR%s away, e.g. %PROGRAMFILES% and so on, in the context when they are permanently saving the PATHs in registry - rendering their Windows installations tainted. In registry, those %%s are still preserved, but in command line, these have been expanded away, so that is why it became so convoluted.

Perhaps the right way is to carefully look if the registration is to be made permanent registry or only local to current prompt, and if only local, then look in `os.getenv` and not in registry at all. PR would be welcome here if that looks like something you already were going for?

**Comment by iboB** [comment]
Sure. I'll do this.
