### ISSUE TITLE
Windows installer?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emsdk#272]
Currently we mostly recommend using git to get the emsdk, and mention as an alternative that people download the zip of the emsdk repo from github.

In https://github.com/emscripten-core/emsdk/pull/271#issuecomment-500696404 @juj mentioned that we used to ship a full NSIS installer, but stopped a while ago. More recently we've shipped portable python with the windows zip. That isn't done in the current zip downloads from github, but maybe we should consider it?

Another option for windows installation might be [scoop](https://twitter.com/FlohOfWoe/status/1137315420413878272) as mentioned by @floooh

**Comment by floooh** [comment]
Just some incoherent thoughts :)

I think it's important to mention that scoop is only one of several options (there's also Chocolatey, and probably some others I don't know). Scoop might appeal to "Mac people" because it's very similar to homebrew)...

I'm quite fond of scoop because it seems to focus a lot on providing a UNIX-y command line environment on Windows (e.g. it has busybox, make, python cmake, ...), so setting up a fresh Windows machine for development is a matter of a few minutes.

On Mac, I can do a ```brew install emscripten```, and this does the initial global emsdk setup. From then on I can use the emsdk command line tool to manage the SDK (or run ```brew uninstall emscripten```). I don't know how maintains the homebrew 'recipe', but it seems to get updated with each new stable release.

A "double-clickable" Windows installer makes sense for the initial install, but OTH the emsdk itself is command-line driven (updating and switching SDKs), so having a simple UI installer just for the initial install might not be enough for a "proper" Windows experience (e.g. people used to the "Windows philosophy" might be asking for more... up to Visual Studio integration ;)

Other SDK UI installers (like Qt's) have something like a mini-package-manager inside the UI installer, it offers a list of SDK versions and components in those SDK versions to install or update. But that's a whole lot of additional work just for a single platform.

**Comment by Boscop** [comment]
Yes, it would be nice to have it installable with scoop. https://github.com/lukesampson/scoop/issues/2346

**Comment by kirawi** [comment]
Any update?

**Comment by aminya** [comment]
I created a chocolatey-package for emsdk! 😃 It simplifies the whole process. You can go ahead and use it: 
https://chocolatey.org/packages/emscripten
(it is not officially approved yet).

**Comment by sbc100** [comment]
Awesome!

Thanks for doing that.  Do you want to add your package to `docs/packaging.md`?

**Comment by aminya** [comment]
Sure! Do you want me to wait for it to gets approved officially first or just add it right now?

**Comment by sbc100** [comment]
Whatever you think best.

**Comment by aminya** [comment]
Emscripten now officially has a chocolatey package:

https://chocolatey.org/packages/emscripten
https://github.com/aminya/chocolatey-emscripten/

I will make a PR documenting these, and I will close this issue.

**Comment by jeffRTC** [comment]
Where is the msi installer?

I can't find it. Did you remove it?

**Comment by aminya** [comment]
@jeffRTC There is a chocolatey package you can use. 
https://chocolatey.org/packages/emscripten
