### ISSUE TITLE
not working after restart  (path variables set properly)

### ISSUE THREAD

**Issue by mohit2399** [emscripten-core/emsdk#459]
everything is properly set. path variable properly set. but then also not working. I didn't use it for 2-3 days and might have restarted it. it worked properly earlier after restarts also. refer screenshot for commands I executed.
![Screenshot (27)](https://user-images.githubusercontent.com/43716571/77825486-ab538300-712f-11ea-8baa-8a658ff193f6.png)

**Comment by sbc100** [comment]
I don't know if emsdk_env.bat works with WSL.    Try `source emsdk_env.sh`.

**Comment by mohit2399** [comment]
permission denied. 
tried with 'sudo' too.

![Screenshot (29)](https://user-images.githubusercontent.com/43716571/77838688-cd7eec80-7193-11ea-9ee4-1562b1f9a55d.png)

**Comment by sbc100** [comment]
It looks like you have something called python3 in your path (`which python3` works) but you can't run it (most likely because its a directory).    You might need to figure out the best way to run python3 from the emsdk shell script.   

In the past we've had issues with people using MINGW and python because the environment is MINGW but the python executable is normal windows binary (I'm not sure if there is MINGW version of python out there? .   So you mileage may very doign down this route.

Would you be interested in helping us better support MINGW?   Can I ask why you are trying to make this work under MINGW?   (Would WSL be a suitable replacement?)

**Comment by mohit2399** [comment]
I generally use Linux for programming. Whenever I use Windows, I have to move to the working directory since 'cmd' does not give an option just like 'open terminal here'. But GIT BASH can do this, so I use it. 
No, I am not into Windows Application Development. But If I switch to it, I will surely look into this problem.

**Comment by sbc100** [comment]
Can you tried WSL?  I think this current and best way to get a bash shell on windows now.  I wonder if using WSL would solve your problems and give you a nicer (more linux-like) environment.

I'm kind of hoping we can support WSL and drop all support for both MINGW and MSYS if its true that WSL is better in every way.  But I don't know enough about the landscape myself.

**Comment by mohit2399** [comment]
No, I didn't try WSL. WSL can solve problems but I just need a simple functionality of right-clicking and open terminal here so I didn't have to write the same commands to go into that directory. Git Bash solves the problem but creates some new ones. 

I don't know about WSL much so I am not the right person right now to support WSL.
