### ISSUE TITLE
version 2.0.4 fails producing .bc, but creates wasm and js instead

### ISSUE THREAD

**Issue by 3d4m-vladimir** [emscripten-core/emsdk#620]
I have cmake file with configuration:

```
project(XYZ)

add_library(${PROJECT_NAME} STATIC ${SOURCES})

set(EMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES ON)
set(CMAKE_AR "emcc")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".bc")
set(CMAKE_CXX_CREATE_STATIC_LIBRARY "<CMAKE_AR> -o <TARGET> <LINK_FLAGS> <OBJECTS>")

set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "${EMSCRIPTEN_OPTIONS} \
                                                                     -s WASM=1 \
                                                                     -s BINARYEN_METHOD='native-wasm'")
target_link_options(${PROJECT_NAME} PRIVATE "SHELL:--bind -s MODULARIZE=1 -s WASM=1 -s ENVIRONMENT=node -s BINARYEN_ASYNC_COMPILATION=0")
```

Before 2.0.4 settings above was capable of producing .bc library, but with 2.0.4 (latest) .wasm and .js only.

How I can fix it without reverting to 2.0.3?

**Comment by sbc100** [comment]
If you want to continue to use "bitcode" files rather than actual ar archive you can fix by adding `-r` to your `CMAKE_CXX_CREATE_STATIC_LIBRARY`. 

However the correct fix I believe is to just remove all the `set` lines.  This will result building libraries as ar archives as is normal for native toolchains.

You can also remove the set_target_properties line because  `-s WASM=1 -s BINARYEN_METHOD='native-wasm'` are not needed anymore.
