### ISSUE TITLE
emmake+wasm-ld wrong command generation and link failure

### ISSUE THREAD

**Issue by sandeep-gh** [emscripten-core/emsdk#715]
Trying to build agar (a gui library over sdl) using emconfigure and emmake:
```
emconfigure ./configure --with-sdl=2.0 --without-freetype --prefix=/home/kabira/opensourceforgery/libagar/
emmake make depend all
```
It fails at link step with error: 
```
wasm-ld: error: cannot open /home/kabira/opensourceforgery/libagar//lib: Is a directory
```
on the command
```
emcc: error: '/media/kabira/home/opensourceforgery/emscripten/emsdk/llvm/git/build_main_64/bin/wasm-ld -o libag_vg.so.6.0.0 /home/kabira/opensourceforgery/libagar//lib vg.o vg_circle.o vg_arc.o vg_line.o vg_point.o vg_snap.o vg_tables.o vg_text.o vg_polygon.o vg_view.o vg_tool.o vg_circle_tool.o vg_line_tool.o vg_point_tool.o vg_proximity_tool.o vg_text_tool.o vg_arc_tool.o vg_polygon_tool.o vg_select_tool.o --relocatable -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --lto-legacy-pass-manager' failed (1)
```
For some reason the target directory is being provided ahead of the target file.

**Comment by sbc100** [comment]
I fear that it may be up to you to dig into exactly what is going wrong here.  Autoconf and automake are notoriously complicated collections of scripts.  Its hard to say exactly what is going wrong that can leads to this error.

One thing I recommend to all autoconf users is to try adding `--disable-shaed` since emscripten doesn't support shared libraries in the traditional sense the autoconf expects.

**Comment by sandeep-gh** [comment]
Yes. This was a non-issue. Just tried that and that works. Thank you.
