### ISSUE TITLE
"missing declaration for emcc$export$dynCall_vi" if use SDL_Init(...) since emsdk 2.0.16

### ISSUE THREAD

**Issue by PowerNow** [emscripten-core/emsdk#782]
Hi, since I updated from emsdk 2.0.1 to 2.0.16 on Win10 I'm getting during compilation the warning:
`metadce: missing declaration for emcc$export$dynCall_vi`

The reason is SDL_INIT(). I tried it with SDL_INIT_VIDEO and SDL_INIT_EVERYTHING.
```
int main() {
    SDL_Init(SDL_INIT_VIDEO);
    return 0;
}
```
My emcc command is
`emcc -s main.cpp C:\Programs\glm-0.9.9.8\glm -lidbfs.js -s INITIAL_MEMORY=128MB -s ALLOW_MEMORY_GROWTH=1 -s USE_SDL=2 -s USE_SDL_TTF=2 -s USE_ZLIB=1 -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s FETCH=1 -s EXPORTED_FUNCTIONS="['_main']" -s NO_EXIT_RUNTIME=1 -s EXTRA_EXPORTED_RUNTIME_METHODS="['cwrap']" -O3`

What can be the reason for that? Thks...

**Comment by kripken** [comment]
That warning is safe to ignore.

I believe the underlying issue is that SDL2 has `dynCall("vi" ..)` or `dynCall_vi(..)` calls, but there is no function with the signature `vi`. So that code will never be reached, but metadce doesn't know that.

I don't think it's practical to make that warning 100% precise, and it hasn't been useful, so perhaps we should just remove it.

**Comment by PowerNow** [comment]
Will this issue be solved in the next emscripten version 2.0.17 or can I self somehow remove this warning?

**Comment by kripken** [comment]
https://github.com/emscripten-core/emscripten/pull/13834 should fix this. Until then you can modify the code manually (there is no flag for it).
