### ISSUE TITLE
run .wasm file error

### ISSUE THREAD

**Issue by Crusoekid** [emscripten-core/emsdk#783]
i use emcc .\hello.c -O0 -s WASM=1 -s SIDE_MODULE=1 -o hello.html to generate .js and .wasm

test.js:22 Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="wasi_snapshot_preview1" error: module is not an object or function

**Comment by sbc100** [comment]
If you want to build a stand alone wams module you should probably be using the `-s STANDALONE_WASM` option instead of the `-s SIDE_MODULE` option.  Also you don't need `-s WASM` as this is the default.

Finally, we use `wasi_snapshot_preview1` for some of the imports to conform with the WASI standard.  If you want to successfully load the module without using the JS generated by emscripten then you yourself will need to implement these APIs (or find implementations of them from somewhere).   Its far easier to use the emscripten-generated JS if you are running in JS environment.
