### ISSUE TITLE
Warning starting with 2.0.25: unsupported syscall: __sys_mlock

### ISSUE THREAD

**Issue by woodser** [emscripten-core/emsdk#865]
After updating to 2.0.25, I receive these warnings repeatedly when running the compiled WASM:

```
warning: unsupported syscall: __sys_mlock
warning: unsupported syscall: __sys_munlock
```

Reverting to <2.0.25 resolves the warnings.

**Comment by sbc100** [comment]
These warning as telling you that you code has calls to these unsupported syscalls and that you might want to look at patching your code to avoid these (since calling them does nothing).

I can see now that we probably should have made these warning messages such that they only show up when ASSERTIONS are enabled, or at least have some way to disable them.
