### ISSUE TITLE
How to use js-library and post js with cmake and emsdk

### ISSUE THREAD

**Issue by aykejriw-ms** [emscripten-core/emsdk#948]
I am trying to compile c++ code using emsdk via cmake. 
I am trying  to use js-library and post-js as emsdk flag. But, I am getting below error saying no input files after building to 100%.

`[100%] Linking CXX executable ../output/test.js
em++: error: no input files
CMakeFiles/test.dir/build.make:356: recipe for target '../output/pimWasm.js' failed
make[2]: *** [../output/test.js] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/test.dir/all' failed
make[1]: *** [CMakeFiles/test.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
`

`set(EMCC_LINKER_FLAGS "-s WASM=1  --bind
--js-library  ${CMAKE_SOURCE_DIR}/js/file1.js
--post-js  ${CMAKE_SOURCE_DIR}/js/file2.js
--post-js  ${CMAKE_SOURCE_DIR}/js/file3.js")`
add_executable(test ${HEADERS} ${SOURCES}
          )
set_target_properties(test PROPERTIES LINK_FLAGS ${EMCC_LINKER_FLAGS})`

**Comment by aykejriw-ms** [comment]
@kripken any idea?

**Comment by sbc100** [comment]
One thing to try is to remove the spaces in your link flags to ensure they don't get re-ordered.   So for example `-s WASM=1` would becoming `-sWASM=1` (or just remove that since its the default) and `--js-library ${CMAKE_SOURCE_DIR}/js/file1.js` would become `--js-library=${CMAKE_SOURCE_DIR}/js/file1.js` and `--post-js ${CMAKE_SOURCE_DIR}/js/file3.js"` would become `--post-js=${CMAKE_SOURCE_DIR}/js/file3.js`.

The next thing to try would be to either use `-G Ninja`, to use the nina build tool, or run make with `VERBOSE=1` so that it actually shows you the full command that is failing and you can include that here: https://bytefreaks.net/programming-2/make-building-with-cmake-verbose

**Comment by aykejriw-ms** [comment]
@sbc100 Thank you for the reply. With space reduction and ninja I was able to build .

Just another small problem occurred while making HTTP request.
below is the error:

`popup.html:1 Access to XMLHttpRequest at 'file:///home/ayushi/test.js.mem' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, edge, https, chrome-untrusted.
pimWasm.js:21 Uncaught Error: could not load memory initializer file:///home/ayushi/test.js.mem
    at XMLHttpRequest.<anonymous> (test.js:21)
(anonymous) @ test.js:21
error (async)
readAsync @ test.js:1
doBrowserLoad @ test.js:21
runMemoryInitializer @ test.js:21
receiveInstance @ test.js:21
receiveInstantiationResult @ test.js:21
Promise.then (async)
instantiateArrayBuffer @ test.js:21
instantiateAsync @ test.js:21
createWasm @ test.js:21
(anonymous) @ test.js:21
pimWasm.js:1 GET file:///home/ayushi/test.js.mem net::ERR_FAILED`

**Comment by sbc100** [comment]
In general you don't use WebAssembly via the file:// .. you need to run an `http://` server.  One simple way to do this to use `emrun` that comes with emscripten: https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-run-a-local-webserver-for-testing-why-does-my-program-stall-in-downloading-or-preparing

**Comment by sbc100** [comment]
Seems like the original issue is resolved and this bug can be closed?
