### ISSUE TITLE
can't build emsdk on win10

### ISSUE THREAD

**Issue by sonygod** [emscripten-core/emsdk#967]
c:\>git clone https://github.com/emscripten-core/emsdk.git

c:\>cd emsdk

c:\emsdk>git pull

c:\emsdk>emsdk install latest

     python: can't open file '/c/emsdk/c:\emsdk\emsdk.py': [Errno 2] No such file or directory

c:\emsdk>python --version
Python 3.9.9

**Comment by sbc100** [comment]
Do you have any idea where the `/c/emsdk` part of that path might be coming from?   Could be that you using a cygwin version of python perhaps?  What does `where python` say?   IIUC its best if you use a windows-native version of python.

You could also try running emsdk.py yourself rather than running via `emsdk.bat` which is what the above command is trying to do (e.g. try running  `> python emsdk.py`).

**Comment by sonygod** [comment]
you're right. my python was install by mysys2, I use native python instead mysys2's python .done!
