### ISSUE TITLE
Console emulators causes scripts to recursively launch python processes

### ISSUE THREAD

**Issue by Querijn** [emscripten-core/emsdk#987]
Hey there,

it seems that several console emulators seem to fail to launch just one python process, and instead recursively launch new ones, slowly locking up the computer after a while.

OS: Windows 10
Affects Powershell and cmd

Repro steps:
1. Obtain CMDer, or the Visual Studio Code command line emulator (press CTRL + ` in a window)
2. Follow the "Download and install" instructions until the `emsdk install latest` instruction. It's highly advised not to run this, as it spawns several instances of the python process, which all seems to start downloading latest.
3. Instead, open task manager, sort processes by name, go to P. 
4. Run `emsdk list`
5. Watch as the command emulator does not show any output, but `python emsdk list` processes keep launching in task manager.
6. I recommend closing the console here, after confirming it.

This issue seems to not occur before another emsdk installation, which seems to be on the following commit: https://github.com/emscripten-core/emsdk/commit/060b48f0c69827f95c8433ee965656babf953e82

**Comment by kripken** [comment]
The mentioned commit only corrects a typo in docs, so I think we need a full bisection here to find the actual problem commit. That's fairly fast, and is what I'd recommend if this regressed for you.

https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by Querijn** [comment]
The commit in question was my last known-good commit. It was there to help with the process of searching the failing commit.

**Comment by sbc100** [comment]
It seems like perhaps an oddity of the terminal you are using and unlikely to be the result of 060b48f.

There should only ever be one python process involved when running `emsdk`.    Does it issue still occur if you explicitly run the `.py` file via python (e.g.  `python emsdk.py list`) rather than via the emsdk.bat launcher script?

When you there are processes called in your task manager called `python emsdk list`.. is there no `.py` extension in there?  i.e. is it not `python emsdk.py list`?
